### ISSUE TITLE
There is a crash issue on Android~

### ISSUE THREAD

**Issue by CodeMasterYi** [tapsellorg/TapsellPlusSDK-UnitySample#10]
Cellphone info: sharp shv42 (Android 10)
```
2020-11-08 09:11:00.059 6766-7009/? E/AndroidRuntime: FATAL EXCEPTION: pool-11-thread-1
    Process: com.dreamhomematch.casual.free.cb, PID: 6766
    java.lang.SecurityException: Not allowed to access cell info
        at android.os.Parcel.createException(Parcel.java:2071)
        at android.os.Parcel.readException(Parcel.java:2039)
        at android.os.Parcel.readException(Parcel.java:1987)
        at com.android.internal.telephony.ITelephony$Stub$Proxy.getAllCellInfo(ITelephony.java:8318)
        at android.telephony.TelephonyManager.getAllCellInfo(TelephonyManager.java:5257)
        at ir.tapsell.sdk.c.a.c$c.a(Unknown Source:0)
        at ir.tapsell.sdk.c.a.c.d(Unknown Source:10)
        at ir.tapsell.sdk.c.a.b.a(Unknown Source:27)
        at ir.tapsell.sdk.c.i.a(Unknown Source:16)
        at ir.tapsell.sdk.c.c.b(Unknown Source:83)
        at ir.tapsell.sdk.f.a(Unknown Source:35)
        at ir.tapsell.sdk.f.a(Unknown Source:7)
        at ir.tapsell.sdk.Tapsell.initialize(Unknown Source:2)
        at ir.tapsell.plus.imp.tapsell.c.a(TapsellImp.java:63)
        at ir.tapsell.plus.imp.tapsell.c.<init>(TapsellImp.java:56)
        at ir.tapsell.plus.imp.tapsell.c.a(TapsellImp.java:43)
        at ir.tapsell.plus.d.b(InitAdNetworks.java:153)
        at ir.tapsell.plus.d.c(InitAdNetworks.java:46)
        at ir.tapsell.plus.d.lambda$GzFtn-4c_kylDP3BAsWiqtYRzbo(Unknown Source:0)
        at ir.tapsell.plus.-$$Lambda$d$GzFtn-4c_kylDP3BAsWiqtYRzbo.run(Unknown Source:4)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2020-11-08 09:11:00.059 6766-6823/? E/Tapsell: Tapsell initialize function should be called in onCreate method of your Application class. In the next version of tapsell this will cause error.
2020-11-08 09:11:00.062 4212-4563/? E/PhoneInterfaceManager: [PhoneIntfMgr] getCarrierPrivilegeStatus: No UICC
2020-11-08 09:11:00.064 6766-6823/? D/ConnectivityManager: getMobileDataEnabled()+ subId=3
2020-11-08 09:11:00.064 6766-6823/? D/ConnectivityManager: getMobileDataEnabled()- subId=3 retVal=true
2020-11-08 09:11:00.087 6766-6966/? W/System: Ignoring header Cookie because its value was null.
2020-11-08 09:11:00.089 3070-7027/? E/ResolverController: No valid NAT64 prefix (114, <unspecified>/0)
2020-11-08 09:11:00.109 6766-6823/? E/Unity: AndroidJavaException: java.lang.SecurityException: Not allowed to access cell info
    java.lang.SecurityException: Not allowed to access cell info
        at android.os.Parcel.createException(Parcel.java:2071)
        at android.os.Parcel.readException(Parcel.java:2039)
        at android.os.Parcel.readException(Parcel.java:1987)
        at com.android.internal.telephony.ITelephony$Stub$Proxy.getAllCellInfo(ITelephony.java:8318)
        at android.telephony.TelephonyManager.getAllCellInfo(TelephonyManager.java:5257)
        at ir.tapsell.sdk.c.a.c$c.a(Unknown Source:0)
        at ir.tapsell.sdk.c.a.c.d(Unknown Source:10)
        at ir.tapsell.sdk.c.a.b.a(Unknown Source:27)
        at ir.tapsell.sdk.c.i.a(Unknown Source:16)
        at ir.tapsell.sdk.c.c.b(Unknown Source:83)
        at ir.tapsell.sdk.f.a(Unknown Source:35)
        at ir.tapsell.sdk.f.a(Unknown Source:7)
        at ir.tapsell.sdk.Tapsell.initialize(Unknown Source:2)
        at ir.tapsell.plus.imp.tapsell.c.a(TapsellImp.java:63)
        at ir.tapsell.plus.imp.tapsell.c.<init>(TapsellImp.java:56)
        at ir.tapsell.plus.imp.tapsell.c.a(TapsellImp.java:43)
```

**Comment by CodeMasterYi** [comment]
I think you should remove `TapsellPlusSDK-UnitySample/README_EN.md`, if you don't provide support to it!!!=。=
